import Menu from '@/components/layout/menu/Menu'
import './globals.css'
import { Inter } from 'next/font/google'
import Separator from '@/components/shared/separator/Separator'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Menu />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
